# Generated by Django 6.0.6 on 2026-06-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="books/pdfs/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/covers/"),
        ),
    ]
