# Generated by Django 6.0.6 on 2026-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_notification_tagfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingprogress",
            name="total_pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
